mysite/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('getUserId/', views.getUserIdView.as_view(), name='get_userid'),
    path('milks/', views.MilkList.as_view()),
    path('milks/<int:pk>/', views.MilkDetail.as_view()),   
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('blog/', views.BlogList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mysite/gamification/urls.py
from django.urls import path
from . import views

app_name = 'gamification'
urlpatterns = [
    path('', views.main, name='main'),
    # challenges
    path('challenge/<slug:slug>', views.show_challenge, name='show_challenge'),
    path('challenge/<slug:slug>/details', views.get_challenge_details, name='get_challenge_details'),
    path('challenge/<slug:slug>/<int:image_id>', views.show_image, name='show_image'),
    path('delete-image/<int:image_id>', views.delete_image, name='delete_image'),
    path('send-challenge-photo/<int:challenge_id>', views.send_challenge_photo, name='send_challenge_photo'),

    # likes
    path('like/', views.like, name='like'),
    path('like-image/', views.like_image, name='like_image'),
    # comments
    path('save-comment/', views.save_comment, name='save_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('image-save-comment/', views.image_save_comment, name='image_save_comment'),
    # profile
    path('redirecttouserprofile/', views.redirecttouserprofile, name='redirecttouserprofile'),
    path('profile/<username>', views.profile, name='profile'),
    path('profile-settings/<username>', views.profile_settings, name='profile_settings'),
    # leaderboard
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('leaderboard/<int:year>/', views.leaderboardbyyear, name='leaderboardbyyear'),
    # contact form
    path('contact-form', views.contact_form, name='contact_form'),
    # weeklyquestion
    path('question/', views.get_question, name='weeklyquestion'),
    # imaginequestion
    path('imaginequestion/', views.lastimaginequestion, name='lastimaginequestion'),
    path('imaginequestionmain/', views.imaginequestionmain, name='imaginequestionmain'),
    path('imaginequestion/<int:imagine_id>', views.imaginequestion, name='imaginequestion'),
    # dailysleep
    path('dailysleep/', views.dailysleep, name='dailysleep'),

    # dailymilk
    path('dailymilk/', views.dailymilk, name='dailymilk'),

    #monthlyentries

    path('monthlypoints/', views.monthlyUserPoints, name='monthlypoints'),
    
    path('profileapi/', views.ProfileView.as_view(), name='profileapi'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('gamification/', include('gamification.urls')),
    path('notifications/', include('notifs.urls')),
    path('api/', include('api.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/yaratici/urls.py
from django.urls import path
from . import views

app_name = 'yaratici'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('anasayfa/', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('hayalgucusorusu/', views.imaginequestion, name='imaginequestion'),
    path('hayalgucusorusu/save', views.imaginequestion_save_comment, name='imaginequestion_save_comment'),
    path('hayalgucusorusu/delete', views.delete_comment, name='delete_comment'),
    path('posts/<int:year>', views.posts_byyear, name='posts_byyear'),
    path('posts/<slug:slug>', views.posts_bytag, name='posts_bytag'),
    path('question/', views.get_question, name='get_question'),
    path('results/<int:question_id>', views.question_results, name='question_results'),
    path('post/<slug:slug>', views.show_post, name='show_post'),
    path('cerez-politikasi', views.cerez, name='cerez'),
    # path('add-message/', views.add_message, name='add_message'),
    # path('conduct-quiz/<int:quiz_id>', views.conduct_quiz, name='conduct_quiz'),
    # path('scores/<int:quiz_id>', views.score, name='score'),
    # path('start/', views.start, name='start'),
    # path('create-quiz/', views.create_quiz, name='create_quiz'),
    # path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete_quiz'),
] 

mysite/gamification/models.py
from yaratici.models import BlogPost, Question, ImagineQuestion
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

import sys
from PIL import Image,ImageOps
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
def user_directory_path(instance,filename):
    return f'user_{instance.user.username}/{filename}'

def profile_directory_path(instance,filename):
    return f'user_{instance.user.username}/profilepics/{filename}'


class Milk(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    drankmilk = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user)+" "+str(self.drankmilk)+" "+str(self.date.day)



class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,)
    profile_pic = models.ImageField(upload_to=profile_directory_path,default="default_img.jpg")
    date = models.DateTimeField(auto_now_add=True, null= True)
    description = models.CharField(max_length=200, null=True, blank=True)
    childname = models.CharField(max_length=50, null=True, blank=True)  
    birthday = models.DateField(null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True) 

    
    def save(self):
        im = Image.open(self.profile_pic)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        output = BytesIO()
        print(im.width)
        print(im.height)
        # im = im.resize( (500,500) )
        im.save(output, format='JPEG', quality=30)
        output.seek(0)
        self.profile_pic = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.profile_pic.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
        super(Profile,self).save()
        


class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to=user_directory_path)
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()
    image_likes = models.ManyToManyField( User, blank=True, related_name='likes')



    def __str__(self):
            return self.title

    def get_absolute_url(self):
        return reverse('gamification:show_challenge', kwargs={'slug':self.slug})   

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')		
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=40)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(Challenge,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(Challenge,self).save()

class ImageNominate (models.Model):
    caption = models.CharField(max_length=150, blank=True, verbose_name="Fotoğrafınızın İsmi")
    owner = models.CharField(max_length=150, blank=True, verbose_name="Eser Sahibi 😊")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='challenge_img')
    image_likes = models.ManyToManyField( User, blank=True, related_name='photo_likes')

    def __str__(self):
        return self.caption

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=40)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImageNominate,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImageNominate,self).save()



class Comment (models.Model):
    comment = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ForeignKey(ImageNominate, on_delete=models.CASCADE, blank=True, null=True)
    imaginequestion = models.ForeignKey(ImagineQuestion, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

class ScoringActivities(models.Model):
    title = models.CharField(max_length=255)
    score = models.IntegerField(default=1)

    def __str__(self):
        return self.title

class ScoreBoard (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.ForeignKey(ScoringActivities, on_delete=models.CASCADE,null=True)
    date = models.DateTimeField(auto_now_add=True)
    challenge = models.ForeignKey(Challenge, on_delete=models.CASCADE, null=True)
    imagenominate = models.ForeignKey(ImageNominate, on_delete=models.SET_NULL, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.SET_NULL, null=True)
    deleted = models.BooleanField(default=False)
    weeklyquestion = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True)
    blogpost = models.ForeignKey(BlogPost, on_delete=models.SET_NULL, null=True)
    imaginequestion = models.ForeignKey(ImagineQuestion, on_delete=models.SET_NULL, null=True)
    totalscore = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)+str(self.user)+str(self.activity)


class Mood(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    mood = models.IntegerField()

    def __str__(self):
        return str(self.user)+" "+str(self.mood)+" "+str(self.date.day)

mysite/yaratici/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

import sys
from PIL import Image,ImageOps
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()

    def __str__(self):
            return self.title


class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    meta_title = models.CharField(max_length=255)
    meta_tags = models.CharField(max_length=255,blank=True)
    photo = models.ImageField(upload_to='blog_img')
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(blank=True,null=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE,blank=True,null=True )
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()
    
    def __str__(self):
            return self.title

    def get_absolute_url(self):
        return reverse('yaratici:show_post', kwargs={'slug':self.slug})

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=50)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(BlogPost,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(BlogPost,self).save()




from datetime import timedelta 


class Question(models.Model):
    question = models.CharField(max_length=255)
    blogpost = models.ForeignKey('BlogPost',on_delete=models.PROTECT, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.question


class Choices(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice = models.CharField(max_length = 250)
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

class Challange(models.Model):
    name = models.CharField(max_length = 250)
    description = RichTextField(blank=True,null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=True)
    photo = models.URLField(max_length=250)
    youtube_link = models.CharField(max_length = 500)

    def __str__(self):
        return self.name



class ImagineQuestion(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='imaginequestion_img')
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()
    
    def __str__(self):
            return self.title

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=50)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImagineQuestion,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImagineQuestion,self).save()

mysite/templates/gamification/get-challenge-details.html
{%extends '../base.html'%}
{%load static   %}
{%block css%}

<link rel="stylesheet" type="text/css" href="{% static 'gamification/css/cards.css' %}">
<style>
  .head,
  .flex {
    display: flex;
  }

  .dots {
    float: right;

  }

  #text {
    text-align: center;
  }

  .user_stories {
    border-style: solid;
    border-color: lightgray;
    border-radius: 5px;
    border-width: thin;
  }

  .jumbotron {
    background-color: white;
    text-align: center;
  }

  #md {
    float: right;
    color: red;
  }

  .dots {
    padding-left: 600px;
    padding-top: 20px;
  }

  #fix {
    position: sticky;
  }
</style>

<style>
  body {

    background-color: #cccccc;
  }

  .side,
  .flex {
    display: flex;
  }


  .bord {
    border-style: solid;
    border-color: lightgray;
    border-left: none;
    border-top: none;
    border-radius: 5px;
    border-width: thin;
    border-radius: 5px;
    background-color: white;
  }

  #side {
    overflow: auto;
    max-height: 800px;
  }

  p {
    margin-bottom: 0px;
  }

  .g-color-gray-dark-v4 {
    color: #777 !important;
  }

  .g-font-size-12 {
    font-size: 0.85714rem !important;
  }

  .form-row {
    margin-right: 0px;
    margin-left: 0px;
  }
</style>
{%endblock%}

{%block content%}

<div class="container-fluid">
  <div class="row">
    <div class=""></div>

    <div class="col-lg-8 mx-auto mt-3 pt-3 bord">

      <div id="side">

        {% if challenge %}

        <div class="d-flex justify-content-left  mb-4">
          <img src="{{challenge.photo.url}}" class="rounded-circle border" alt="{{image.user.profile.profile_pic.url}}"
            width="80" height="80">
          <div class="ml-3">
            <h2 class=" ml-3 pt-2"><small><strong>{{challenge.title}}</strong></small></h2>
            <p class=" ml-3">{{challenge.message|safe}}</p>
            

          </div>

        </div>

        <div class="d-flex align-items-baseline pl-3 mb-5">
          <a href="{%url 'gamification:show_challenge' slug=challenge.slug %}"
            class="btn btn-primary btn-fill btn-round mr-2"> Fotoğraflar</a>
          <a href="{%url 'gamification:send_challenge_photo' challenge_id=challenge.id %}"
            class="btn btn-warning btn-fill btn-round"><i class="fas fa-user-plus"></i> Katıl</a>

        </div>

        <!-- comment form -->
        <div class=" comments mb-3 ">
          {%if user.is_authenticated %}
          <form id="post-form" enctype="multipart/form-data" method="post" action="">
            {% csrf_token %}
            <div class="form-row">
              <div class="col-sm-9 mb-3">{{form.as_p}}</div>
              <div class="col-sm-2 "><input id="challengeid" name="{{challenge.id}}" class="btn btn-primary sendcomment "
                  type="submit" value="Gönder"></div>
            </div>
          </form>
          {%else%}
          <div class="mb-4">Yorum yapmak için lütfen giriş yapınız. <a href="{%url 'login' %}?next={{request.path}}"> Giriş Yap</a></div>
        </div>
        {%endif%}
        <!-- comment for end -->
        <div id="commentarea">
        </div>
        {% for comment in challenge.comment_set.all reversed%}
        <div id=singlecomment{{comment.id}} class="flex pt-3 ">
          <div>
            <a href="{% url 'gamification:profile' username=comment.user  %}">
              <img src="{{comment.user.profile.profile_pic.url}}" class="rounded-circle border" alt="img" width="40"
                height="40">
            </a>
          </div>
          <div>
            <p class="pl-2"><span class="font-weight-bold">{{comment.user.username}}</span> {{comment.comment}}
              <br><span class="g-color-gray-dark-v4 g-font-size-12">{{comment.date|timesince }}</span>
              {% if request.user == comment.user %}
              <span><a class="deletecomment" name={{comment.id}} href="" class="  pr-2"> <i class="fas fa-trash"></i>
                </a></span>
              {%endif%}</p>

          </div>
        </div>
        <hr>
        {% endfor %}
        {% else %}
      </div>
      <h6 class="text-center">Henüz bir yorum yapılmamış</h6>
      {% endif %}
    </div>

  </div>
</div>

<!-- comments end -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
  $('.deletecomment').on('click', function (event) {
    console.log($(this).attr('name'))
    event.preventDefault();
    if (confirm("Silmek istediğinizden emin misiniz?")) {
      console.log($(this).attr('name'))
      $.ajax({
        url: "{% url 'gamification:delete_comment' %}", // the endpoint
        type: "POST", // http method
        data: {
          'content_id': $(this).attr('name'),
          'operation': 'delete_challenge_comment',
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        }, // data sent with the post request

        // handle a successful response
        success: function (json) {
          console.log(json)
          $("#singlecomment" + json.comment_id).remove();
          
        },

        // handle a non-successful response
        error: function (xhr, errmsg, err) {
          $('#results').html(
            "<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " +
            errmsg +
            " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
          console.log(xhr.status + ": " + xhr
            .responseText); // provide a bit more info about the error to the console
        }
      });
    } else {
      txt = "You pressed Cancel!";
    }

  });
</script>


<script>
  $('#post-form').on('submit', function (event) {
    event.preventDefault();
    $.ajax({
      url: "{% url 'gamification:save_comment' %}", // the endpoint
      type: "POST", // http method
      data: {
        'content_id': $('#challengeid').attr('name'),
        'comment': $('#post-text').val(),
        'operation': 'send_comment',
        'csrfmiddlewaretoken': '{{ csrf_token }}'
      }, // data sent with the post request

      // handle a successful response
      success: function (json) {
        $('#post-text').val(''); // remove the value from the input
        console.log(json); // log the returned json to the console
        $("#commentarea").prepend(
          '<div class="flex ">          <div>            <a href="% url "others_profile" comment.user.id  %}">              <img src="'+json.imgpath +'"                class="rounded-circle border" alt="img" width="40" height="40">            </a></div>          <div>            <p class="ml-2"><span class="font-weight-bold">' +
          json.user + '</span> ' + ' ' + json.text + '<br><span class="g-color-gray-dark-v4 g-font-size-12">0 dakika</span></p>          </div>        </div><hr>');
      },

      // handle a non-successful response
      error: function (xhr, errmsg, err) {
        $('#results').html(
          "<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " +
          errmsg +
          " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
        console.log(xhr.status + ": " + xhr
          .responseText); // provide a bit more info about the error to the console
      }
    });
  });

  function create_image_comment() {

  };
</script>

{%endblock%}

mysite/templates/gamification/main.html
{%extends '../base.html'%}
{%load static   %}

{%block css%}
<link rel="stylesheet" type="text/css" href="{% static 'gamification/css/cards.css' %}">

<style>
    .media-comment {
        margin-top: 20px
    }


    #pcomment {
        margin-bottom: 0px;
    }

    .commentbox .bold {
        font-weight: 600;
        font-size: 14px;
        color:  #3C424F;
    }

    .commentbox .description {

        font-size: 14px;
        color:  #6B7C93;;
    }

    p {
        margin-bottom: 0.1rem;
        margin-top: 0.1rem;
    }

    #likescard {
        font-size: 14px;
    }
    .card a:hover, .card a:focus {
        color: #7380C6
    }
</style>


{%endblock%}

{%block content %}


<div class="row mt-5">
    {%for challenge in challenges %}
    <div class="card-box col-lg-4 col-md-6 col-sm-12">
        <div class="card">
            <div style=" background-image: url('{{challenge.photo.url}}'); background-position: center center; background-size: cover;"
                class="header"> <a style="margin:0 auto;display:block;width:100%;height:250px"class="stretched-link"href="{%url 'gamification:show_challenge' slug=challenge.slug %}"></a>
                <div class="social-line social-line-visible" data-buttons="4">
                    
                    <button name="{{ challenge.id }}" class="likin btn btn-social btn-facebook">
                        {%if user in challenge.image_likes.all %}
                        <i name="likebtn{{ challenge.id }}" style="color: red;" class=" fas fa-heart"></i>
                        {%else %}
                        <i name="likebtn{{ challenge.id }}" style="color: red;" class=" far fa-heart"></i>
                        {%endif%}

                        <span id="likecounts{{ challenge.id }}">{{challenge.image_likes.count}}</span>
                    </button>
                    <a href="{%url 'gamification:get_challenge_details' slug=challenge.slug %}">
                        <button class="btn btn-social btn-twitter">
                            <i class="far fa-comment"></i>
                            <span id="likecounts{{ challenge.id }}">{{challenge.comment_set.count}}</span>
                        </button></a>
                    <button class="btn btn-social btn-twitter">
                        <a href="{%url 'gamification:leaderboard' %}"><i style="color: #C0E218"
                                class="fas fa-list-ul"></i></a>

                    </button>
                    <button class="btn btn-social btn-twitter">
                        <a href="{%url 'gamification:send_challenge_photo' challenge_id=challenge.id %}"><i
                                style="color: #222831" class="fas fa-user-plus"></i></a>

                    </button>

                </div>
                
            </div>
            <div id="fixedheight" class="content">

                <h6 class="category ">{{challenge.user}} {{challenge.user.count}}</h6>
                <a href="{%url 'gamification:show_challenge' slug=challenge.slug %}">
                    <h4 class="title">{{challenge.title}}</h4>
                </a>

                <p class="description "> {{challenge.message|truncatewords:10|safe}} <a
                        style="font-size:14px; color: #7380C6; font-weight:bold"
                        href="{%url 'gamification:get_challenge_details' slug=challenge.slug %}">Devamı</a>
                </p>


                <div class="commentbox">
                    {%if challenge.comment_set.all %}
                    <p><span class="bold">{{challenge.comment_set.first.user}}</span> <span
                            class="description">{{challenge.comment_set.first.comment|truncatewords:4|slice:"-1"}}</span></p>
                    <p style="padding:0px"class="description"><a
                            href="{%url 'gamification:get_challenge_details' slug=challenge.slug %}">{{challenge.comment_set.count}}
                            Yorumun tümünü gör</a></p>
                    {%if challenge.comment_set.all.count > 1 %}
                    <p><span class="bold">{{challenge.comment_set.last.user}}</span> <span
                            class="description">{{challenge.comment_set.last.comment|truncatewords:4|slice:"-1"}}</span></p>
                    {%endif%}
                    {%else%}
                    <p><span class="bold"> </span> <span class="description"></span></p>
                    {%endif%}
                </div>

            </div>
            <div class="footer text-center">
                <a href="{%url 'gamification:show_challenge' slug=challenge.slug %}"
                    class="btn btn-info btn-fill btn-round"> Fotoğraflar</a>
                <a href="{%url 'gamification:send_challenge_photo' challenge_id=challenge.id %}"
                    class="btn btn-warning btn-fill btn-round"><i class="fas fa-user-plus"></i> Katıl</a>
            </div>
        </div> <!-- end card -->
        
    </div>
    {%endfor %}


   

</div>




{%endblock%}

{%block script%}

<script>
    // AJAX CALL
    $('.likin').click(function () {
        console.log('click worked')
        $.ajax({
            type: "POST",
            url: "{% url 'gamification:like' %}",
            data: {
                'content_id': $(this).attr('name'),
                'operation': 'like_submit',
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            success: function (response) {
                console.log(response)
                selector = document.getElementsByName("likebtn" + response.content_id);
                likecount = document.getElementById("likecounts" + response.content_id)
                console.log(selector)
                if (response.liked == true) {
                    $(selector).attr("class", "fas fa-heart");
                    $(likecount).text(response.likes_count)


                } else if (response.liked == false) {
                    $(selector).attr("class", "far fa-heart");
                    $(likecount).text(response.likes_count)

                }


            },
            error: function (response) {
                alert('Beğenmek için lütfen giriş yapınız')
            }

        });

    })
</script>
{%endblock%}