mysite/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('getUserId/', views.getUserIdView.as_view(), name='get_userid'),
    path('milks/', views.MilkList.as_view()),
    path('milks/<int:pk>/', views.MilkDetail.as_view()),   
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('blog/', views.BlogList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mysite/gamification/urls.py
from django.urls import path
from . import views

app_name = 'gamification'
urlpatterns = [
    path('', views.main, name='main'),
    # challenges
    path('challenge/<slug:slug>', views.show_challenge, name='show_challenge'),
    path('challenge/<slug:slug>/details', views.get_challenge_details, name='get_challenge_details'),
    path('challenge/<slug:slug>/<int:image_id>', views.show_image, name='show_image'),
    path('delete-image/<int:image_id>', views.delete_image, name='delete_image'),
    path('send-challenge-photo/<int:challenge_id>', views.send_challenge_photo, name='send_challenge_photo'),

    # likes
    path('like/', views.like, name='like'),
    path('like-image/', views.like_image, name='like_image'),
    # comments
    path('save-comment/', views.save_comment, name='save_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('image-save-comment/', views.image_save_comment, name='image_save_comment'),
    # profile
    path('redirecttouserprofile/', views.redirecttouserprofile, name='redirecttouserprofile'),
    path('profile/<username>', views.profile, name='profile'),
    path('profile-settings/<username>', views.profile_settings, name='profile_settings'),
    # leaderboard
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('leaderboard/<int:year>/', views.leaderboardbyyear, name='leaderboardbyyear'),
    # contact form
    path('contact-form', views.contact_form, name='contact_form'),
    # weeklyquestion
    path('question/', views.get_question, name='weeklyquestion'),
    # imaginequestion
    path('imaginequestion/', views.lastimaginequestion, name='lastimaginequestion'),
    path('imaginequestionmain/', views.imaginequestionmain, name='imaginequestionmain'),
    path('imaginequestion/<int:imagine_id>', views.imaginequestion, name='imaginequestion'),
    # dailysleep
    path('dailysleep/', views.dailysleep, name='dailysleep'),

    # dailymilk
    path('dailymilk/', views.dailymilk, name='dailymilk'),

    #monthlyentries

    path('monthlypoints/', views.monthlyUserPoints, name='monthlypoints'),
    
    path('profileapi/', views.ProfileView.as_view(), name='profileapi'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('gamification/', include('gamification.urls')),
    path('notifications/', include('notifs.urls')),
    path('api/', include('api.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/notifs/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('', views.all, name='all'),
    path('unread', views.unread, name='unread'),
    path('mark-as-read/<int:notif_id>', views.mark_as_read, name='mark_as_read'),
    path('mark-all-as-read/', views.mark_all_as_read, name='mark_all_as_read'),
    path('unreadcountajax/', views.unreadcountajax,name='unreadcountajax')
    # path('unread/>', views.unread, name='unread'),

]

mysite/yaratici/urls.py
from django.urls import path
from . import views

app_name = 'yaratici'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('anasayfa/', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('hayalgucusorusu/', views.imaginequestion, name='imaginequestion'),
    path('hayalgucusorusu/save', views.imaginequestion_save_comment, name='imaginequestion_save_comment'),
    path('hayalgucusorusu/delete', views.delete_comment, name='delete_comment'),
    path('posts/<int:year>', views.posts_byyear, name='posts_byyear'),
    path('posts/<slug:slug>', views.posts_bytag, name='posts_bytag'),
    path('question/', views.get_question, name='get_question'),
    path('results/<int:question_id>', views.question_results, name='question_results'),
    path('post/<slug:slug>', views.show_post, name='show_post'),
    path('cerez-politikasi', views.cerez, name='cerez'),
    # path('add-message/', views.add_message, name='add_message'),
    # path('conduct-quiz/<int:quiz_id>', views.conduct_quiz, name='conduct_quiz'),
    # path('scores/<int:quiz_id>', views.score, name='score'),
    # path('start/', views.start, name='start'),
    # path('create-quiz/', views.create_quiz, name='create_quiz'),
    # path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete_quiz'),
] 

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- tags -->
    <title>{% block title %}{% endblock  %}</title>
    <meta name="description" content="{% block meta %}{% endblock  %}">

    <!-- adsense -->
    <script data-ad-client="ca-pub-1218638256754735" async
        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-181247946-1"></script>

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;500;800;900&family=Open+Sans:wght@300;400;600;700&display=swap"rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/8ca48c6d4e.js" crossorigin="anonymous"></script>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- lightbox -->
    <link href="{% static 'gamification/css/lightbox.css' %}" rel="stylesheet" />
    <!-- custom css -->
    <link rel="stylesheet" type="text/css" href="{% static 'gamification/css/gamification.css' %}">
    
    
    <title>Yaratıcı Çocuğum</title>


    {%block css%}{%endblock%}
    
</head>

<body>

    {% include "./header_final.html" %}


    <div class="container">

        {% block content %}
        {% endblock  %}

    </div>

    {% include "./footer_final.html" %}


        <!-- ajax -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- lightbox -->
    <script src="{% static 'gamification/js/lightbox.js' %}"></script>

    <!-- get unread notif -->
    <script>
        $(document).ready(function(){
            $('#headercounter').load("{%url 'notifications:unreadcountajax' %}");
                $.ajax({
                method: "get",url: "{%url 'notifications:unreadcountajax' %}",
                success: function(json)
                        {
                        console.log(json)
                        $("#headercounter").val(json.unreadcount);
                        }
                });
            });
    </script>

    {%block script%}{%endblock%}
</body>

</html>

mysite/templates/footer_final.html
<div class="d-flex align-items-center justify-content-center mt-3 mb-3">
    {% if request.user.is_authenticated %}
    <a class="stickymiobutton"style=" font-size:0.8rem; font-weight:700;"class="ml-5" href="{% url 'gamification:profile' username=user.username %}"><span id="miobuttonbottom"style=""><i class="fas fa-user"></i>  MiO PROFİL</span> </a>
    {%else%}
    <a class="stickymiobutton"style="font-size:0.8rem; font-weight:700;  "class="" href="{% url 'login' %}"><span id="miobuttonbottom"style=""><i class="fas fa-user"></i>  MiO GİRİŞ</span> </a>
    
    {%endif%}
    
</div>

<div class="d-flex align-items-center mt-1">
    <p class="footer footer-simple mx-auto">&copy;&nbsp;&nbsp;2021&nbsp;Yaratıcı Çocuğum&nbsp;
    <a href="{%url 'yaratici:cerez' %}">Çerez Politikası</a>
</p>
</div>

mysite/templates/header-wrapper.html
<div class="header-wrapper">
    <div class='header  color-overlay  custom-mobile-image'
        style='background-image:url("https://yaraticicocugum.com/anasayfa/wp-content/themes/highlight/assets/images/hero-inner.jpg"); background-color:#6a73da'
        data-parallax-depth='20'>
        <div class="background-overlay"></div>
        <div class="inner-header-description gridContainer">
            <div class="row header-description-row">
                <div class="col-xs col-xs-12">
                    <h1 class="hero-title align-center">
                        Haftanın Sorusu </h1>
                        <div id="newquestion"></div>
                </div>
            </div>
        </div>
    </div>
</div>

mysite/templates/header_final.html
{%if 'anasayfa' in request.path %}

{%endif%}







<nav style="background-color:white" class="navbar navbar-expand-lg navbar-light ">
    <a class="navbar-brand" href="{% url 'yaratici:home' %}">Yaratıcı <span style="font-weight: 300;" class="">
            Çocuğum</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="" id="">
        <ul class="navbar-nav ml-auto">

            {%if unreadnotifcount  %}
            <li class="nav-item">
                <a href="{% url 'notifications:all'%}"><button type="button" class="btn btn-light">
                    <i class="fas fa-bell"></i> <span id='headercounter'class="badge badge-light btn-primary">{{unreadnotifcount}}</span>
                  </button></a>
            </li>
            {%else%}
            <li class="nav-item">
                <a href="{% url 'notifications:all'%}"><button type="button" class="btn btn-light">
                    <i class="fas fa-bell"></i> <span id='headercounter'class="badge badge-light btn-primary">{{unreadnotifcount}}</span>
                  </button></a>
            </li>
            {%endif%}

            

        </ul>
    </div>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto  mt-lg-0">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'yaratici:posts' %}">BlOG </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gamification:weeklyquestion'%}">HAFTANIN SORUSU </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'gamification:main'%}">CHALLENGES </a>

            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'gamification:imaginequestionmain'%}">HAYAL GÜCÜ SORUSU </a>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'gamification:contact_form'%}" tabindex="-1"
                    aria-disabled="true">İLETİŞİM</a>
            </li>

            <li class="nav-item">
                <div class="dropdown nav-link">
                    <a class=" dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        {% if request.user.is_authenticated %}
                         <span id="miobutton"><i class="fas fa-user"></i>  {{user.username}}</span>
                        {%else%}
                        <span id="miobutton"style=""><i class="fas fa-user"></i>  MiO GİRİŞ</span> 
                        {%endif%}
                    </a>

                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% if request.user.is_authenticated %}
                        <a class="dropdown-item" href="{% url 'gamification:profile' username=user.username %}"><i class="far fa-id-badge"></i> PROFİL</a>
                        
                        <a class="dropdown-item" href="{% url 'gamification:leaderboard'%}"><i class="fas fa-list-ul"></i> Puan Tablosu </a>
                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> ÇIKIŞ</a>
                        {%else%}
                        <a class="dropdown-item" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> GİRİŞ </a>
                        <a class="dropdown-item" href="{% url 'gamification:leaderboard'%}"><i style="color:#7454AE"class="fas fa-trophy"></i> Puan Tablosu </a>
                        {%endif%}
 
                    </div>
                </div>

        </ul>

    </div>
</nav>


{% if messages %}
{% for message in messages %}


<div class=" alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
    {{ message|safe }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>


{% endfor %}
{% endif %}