mysite/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('getUserId/', views.getUserIdView.as_view(), name='get_userid'),
    path('milks/', views.MilkList.as_view()),
    path('milks/<int:pk>/', views.MilkDetail.as_view()),   
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
    path('blog/', views.BlogList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

mysite/gamification/urls.py
from django.urls import path
from . import views

app_name = 'gamification'
urlpatterns = [
    path('', views.main, name='main'),
    # challenges
    path('challenge/<slug:slug>', views.show_challenge, name='show_challenge'),
    path('challenge/<slug:slug>/details', views.get_challenge_details, name='get_challenge_details'),
    path('challenge/<slug:slug>/<int:image_id>', views.show_image, name='show_image'),
    path('delete-image/<int:image_id>', views.delete_image, name='delete_image'),
    path('send-challenge-photo/<int:challenge_id>', views.send_challenge_photo, name='send_challenge_photo'),

    # likes
    path('like/', views.like, name='like'),
    path('like-image/', views.like_image, name='like_image'),
    # comments
    path('save-comment/', views.save_comment, name='save_comment'),
    path('delete-comment/', views.delete_comment, name='delete_comment'),
    path('image-save-comment/', views.image_save_comment, name='image_save_comment'),
    # profile
    path('redirecttouserprofile/', views.redirecttouserprofile, name='redirecttouserprofile'),
    path('profile/<username>', views.profile, name='profile'),
    path('profile-settings/<username>', views.profile_settings, name='profile_settings'),
    # leaderboard
    path('leaderboard/', views.leaderboard, name='leaderboard'),
    path('leaderboard/<int:year>/', views.leaderboardbyyear, name='leaderboardbyyear'),
    # contact form
    path('contact-form', views.contact_form, name='contact_form'),
    # weeklyquestion
    path('question/', views.get_question, name='weeklyquestion'),
    # imaginequestion
    path('imaginequestion/', views.lastimaginequestion, name='lastimaginequestion'),
    path('imaginequestionmain/', views.imaginequestionmain, name='imaginequestionmain'),
    path('imaginequestion/<int:imagine_id>', views.imaginequestion, name='imaginequestion'),
    # dailysleep
    path('dailysleep/', views.dailysleep, name='dailysleep'),

    # dailymilk
    path('dailymilk/', views.dailymilk, name='dailymilk'),

    #monthlyentries

    path('monthlypoints/', views.monthlyUserPoints, name='monthlypoints'),
    
    path('profileapi/', views.ProfileView.as_view(), name='profileapi'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('courses/', include('courses.urls')),
    path('emailer/', include('emailer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('yaratici.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('gamification/', include('gamification.urls')),
    path('notifications/', include('notifs.urls')),
    path('api/', include('api.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/yaratici/urls.py
from django.urls import path
from . import views

app_name = 'yaratici'
urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('anasayfa/', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('hayalgucusorusu/', views.imaginequestion, name='imaginequestion'),
    path('hayalgucusorusu/save', views.imaginequestion_save_comment, name='imaginequestion_save_comment'),
    path('hayalgucusorusu/delete', views.delete_comment, name='delete_comment'),
    path('posts/<int:year>', views.posts_byyear, name='posts_byyear'),
    path('posts/<slug:slug>', views.posts_bytag, name='posts_bytag'),
    path('question/', views.get_question, name='get_question'),
    path('results/<int:question_id>', views.question_results, name='question_results'),
    path('post/<slug:slug>', views.show_post, name='show_post'),
    path('cerez-politikasi', views.cerez, name='cerez'),
    # path('add-message/', views.add_message, name='add_message'),
    # path('conduct-quiz/<int:quiz_id>', views.conduct_quiz, name='conduct_quiz'),
    # path('scores/<int:quiz_id>', views.score, name='score'),
    # path('start/', views.start, name='start'),
    # path('create-quiz/', views.create_quiz, name='create_quiz'),
    # path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete_quiz'),
] 

mysite/yaratici/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

import sys
from PIL import Image,ImageOps
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField()

    def __str__(self):
            return self.title


class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    meta_title = models.CharField(max_length=255)
    meta_tags = models.CharField(max_length=255,blank=True)
    photo = models.ImageField(upload_to='blog_img')
    create_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    publish_date = models.DateTimeField(blank=True,null=True)
    category = models.ForeignKey(Category, on_delete= models.CASCADE,blank=True,null=True )
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()
    
    def __str__(self):
            return self.title

    def get_absolute_url(self):
        return reverse('yaratici:show_post', kwargs={'slug':self.slug})

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=50)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(BlogPost,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(BlogPost,self).save()




from datetime import timedelta 


class Question(models.Model):
    question = models.CharField(max_length=255)
    blogpost = models.ForeignKey('BlogPost',on_delete=models.PROTECT, blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=False)
    
    
    def __str__(self):
        return self.question


class Choices(models.Model):
    question = models.ForeignKey('Question',on_delete=models.CASCADE)
    choice = models.CharField(max_length = 250)
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

class Challange(models.Model):
    name = models.CharField(max_length = 250)
    description = RichTextField(blank=True,null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=True)
    photo = models.URLField(max_length=250)
    youtube_link = models.CharField(max_length = 500)

    def __str__(self):
        return self.name



class ImagineQuestion(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE )
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='imaginequestion_img')
    create_date = models.DateTimeField(auto_now_add=True)
    is_Published = models.BooleanField(default=False)
    message = RichTextField(blank=True,null=True)
    slug = models.SlugField()
    
    def __str__(self):
            return self.title

    def save(self):
        im = Image.open(self.photo)
        im = ImageOps.exif_transpose(im)
        im = im.convert('RGB')
        
        if im.width > 2000 and im.height> 2000:
            print('big picturee')
            output = BytesIO()
            half = 0.5
            im = im.resize( [int(half * s) for s in im.size] )
        # im = im.resize( (1000,1000) )
            im.save(output, format='JPEG', quality=50)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImagineQuestion,self).save()
        else:
            output = BytesIO()
            im.save(output, format='JPEG', quality=30)
            output.seek(0)
            self.photo = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.photo.name.split('.')[0], 'image/jpeg', sys.getsizeof(output), None)
            super(ImagineQuestion,self).save()

mysite/yaratici/forms.py
from django.forms import ModelForm
from .models import Choices
from django import forms



class ChoiceForm(ModelForm):
    class Meta:
        model = Choices
        fields = ['choice']

mysite/templates/yaratici/bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <meta name="description" content="{% block meta %}{% endblock  %}">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-181247946-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-181247946-1');
    </script>


    <link rel="profile" href="http://gmpg.org/xfn/11">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    {% block css %}{% endblock css %}
</head>

<body>




        {% block content %}
        {% endblock  %}
    </div>



    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
</body>

</html>

mysite/templates/yaratici/header.html
<style>
    .screen-reader-text[href="#page-content"]:focus {
        background-color: #f1f1f1;
        border-radius: 3px;
        box-shadow: 0 0 2px 2px rgba(0, 0, 0, 0.6);
        clip: auto !important;
        clip-path: none;
        color: #21759b;

    }
    #miobutton{
        padding:0.3rem 1rem;
        border-radius:0.5rem; 
        color:white; 
        text-transform: none;
        background: rgb(103,122,228);
                        background: linear-gradient(137deg, rgba(103,122,228,1) 0%, rgba(115,83,173,1) 80%);
    }

    #miobuttonbottom{
        padding:0.3rem 1rem;
        border-radius:1rem; 
        color:white; 
        text-transform: none;
        background: rgb(255,168,162);
        background: linear-gradient(131deg, rgba(255,168,162,1) 0%, rgba(104,119,223,1) 80%);
    }

    ul.dropdown-menu>li>a {
        letter-spacing: 0.2px;
    }
    
</style>

{%if 'anasayfa' in request.path %}
<div id="page-top" class="header-top homepage">
    <div class="navigation-bar homepage">
        {%else%}
        <div id="page-top" class="header-top">
            <div class="navigation-bar coloured-nav" data-sticky='0' data-sticky-mobile='1' data-sticky-to='top'>
               
{%endif%}

        <div class="navigation-wrapper ">
            <div class="row basis-auto">
                <div class="logo_col col-xs col-sm-fit">
                    <a class="text-logo" data-type="group" data-dynamic-mod="true"
                        href="{% url 'yaratici:home' %}">Yaratıcı<span style="font-weight: 300;"
                            class="span12"> Çocuğum</span></a> </div>
                <div class="main_menu_col col-xs">
                    <div id="mainmenu_container" class="row">
                        <ul id="main_menu" class="main-menu dropdown-menu">

                                    <!-- start of gamification -->

                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'yaratici:posts' %}">BlOG </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'gamification:weeklyquestion'%}">HAFTANIN SORUSU </a>
                                    </li>
                        
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'gamification:main'%}">CHALLENGES </a>
                        
                                    </li>
                        
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'gamification:imaginequestionmain'%}">HAYAL GÜCÜ SORUSU </a>
                                    </li>
                        
                        
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'gamification:contact_form'%}" tabindex="-1"
                                            aria-disabled="true">İLETİŞİM</a>
                                    </li>

                                    
                                    {% if request.user.is_authenticated %}
                                    <li class="nav-item">
                                        <a id="miobutton"class="nav-link" href="{% url 'gamification:profile' username=user.username %}" tabindex="-1"
                                            aria-disabled="true"> {{user.username}}</i> </a>
                                    </li>
                                    {%else%}
                                    <li class="nav-item">
                                        <a id="miobutton"class="nav-link" href="{% url 'login' %}" tabindex="-1"
                                            aria-disabled="true"> MiO GİRİŞ</i> </a>
                                    </li>
                                    {%endif%}

                         


                                    <!-- end of gamification -->

                        </ul>
                    </div> <a href="#" data-component="offcanvas" data-target="#offcanvas-wrapper"
                        data-direction="right" data-width="300px" data-push="false">
                        <div class="bubble"></div>
                        <i class="fa fa-bars"></i>
                    </a>
                    <div id="offcanvas-wrapper" class="hide force-hide  offcanvas-right">
                        <div class="offcanvas-top">
                            <div class="logo-holder">
                                <a class="text-logo" data-type="group" data-dynamic-mod="true"
                                    href="#">Yaratıcı<span
                                        style="font-weight: 300;" class="span12"> Çocuğum</span></a> </div>
                        </div>
                        <div id="offcanvas-menu" class="menu-main-menu-container">
                            <ul id="offcanvas_menu" class="offcanvas_menu">

                                <!-- start of gamification -->
                                
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'yaratici:posts' %}">BlOG </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'gamification:weeklyquestion'%}">HAFTANIN SORUSU </a>
                                </li>
                    
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'gamification:main'%}">CHALLENGES </a>
                    
                                </li>
                    
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'gamification:imaginequestionmain'%}">HAYAL GÜCÜ SORUSU </a>
                                </li>
                    
                    
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'gamification:contact_form'%}" tabindex="-1"
                                        aria-disabled="true">İLETİŞİM</a>
                                </li>

                                {% if request.user.is_authenticated %}
                                <li class="nav-item">
                                    <a id="miobutton"class="nav-link" href="{% url 'gamification:profile' username=user.username %}" tabindex="-1"
                                        aria-disabled="true"> {{user.username}}</i> </a>
                                </li>
                                {%else%}
                                <li class="nav-item">
                                    <a id="miobutton"class="nav-link" href="{% url 'gamification:main'%}" tabindex="-1"
                                        aria-disabled="true"> MiO GİRİŞ</i> </a>
                                </li>
                                {%endif%}

                                <!-- end of game -->
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

mysite/templates/yaratici/post.html
{% extends './base.html'%}

{% block title %} {{post.title}} {% endblock  %}
{% block meta %} {{post.meta_title}} {% endblock  %}

{% block css %}{% endblock css %}


{%block content%}


<div id="page" class="site">

    <div class="header-wrapper">
        {%if post.slug == 'ben-kimim' %}
        <div class='header  color-overlay  custom-mobile-image'
        style='background-image:url("media/blog_img/hero-inner.jpg"); background-color:#6a73da' data-parallax-depth='20'>
        {%else%}
        
        <div class='header  color-overlay  custom-mobile-image'style='background-image:url("{{post.photo.url}}"); background-color:#6a73da' data-parallax-depth='20'>
        {%endif%}   
            <div class="background-overlay"></div>
            <div class="inner-header-description gridContainer">
                <div class="row header-description-row">
                    <div class="col-xs col-xs-12">
                        <h1 class="hero-title align-center">
                            {{post.title}} </h1>

                    </div>
                </div>
            </div>
            <script>
                if (window.mesmerizeSetHeaderTopSpacing) {
                    window.mesmerizeSetHeaderTopSpacing();
                }
            </script>
        </div>
    </div>
    <br>
    <br>
    <div id='page-content' class="page-content">
        <div class="gridContainer">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-md-9">

                <h2>{{post.title}}</h2>
                    
                    <img src="{{post.photo.url}}" style="max-width: 100%;width:100%" alt="">
                    <br><br>
                    {{post.message|safe}}
                    <br>
                    <b>Tags:</b>  {{post.meta_tags}}

                    <div style="margin-top:1rem"class="row">
                        <div class="text-center"> <a class="button big color1"
                                data-attr-shortcode="href:mesmerize_blog_link"
                                href="{%url 'yaratici:posts' %}">Diğer Yazılar</a>
                                <a
                                class="button big color1" target="_self"
                                href="{%url 'yaratici:get_question'%}#question">Haftanın Sorusu <i class="far fa-smile-wink"></i> </a>
                                {% if request.user.is_authenticated %}
                                <a
                                class="button big color1" target="_self"
                                href="{% url 'gamification:profile' username=user.username %}">MiO PROFİL</i> </a>
                                {%else%}
                                <a
                                class="button big color1" target="_self"
                                href="{% url 'login' %}">MiO GİRİŞ</i> </a>
                                {%endif%}
                                
                            </div>
                    </div>
                </div>
               
                <div class="sidebar col-sm-4 col-md-3">
                    <div class="panel bg-color-white">
                        
                        <div id="recent-posts-2" class="widget widget_recent_entries">
                            <h5 class="widgettitle">Son Yazılar</h5>
                            <ul>
                                {%for post in sidebarposts%}
                                <li>
                                    <a href="{%url 'yaratici:show_post' slug=post.slug%}"
                                        aria-current="page">{{post.title}}</a>
                                </li>
                                {%endfor%}
                                <li>
                                    <a href="{%url 'yaratici:posts'%}"
                                        aria-current="page"><small> Tüm yazılar</small></a>
                                </li>
                            </ul>

                        </div>
                       
                        <div id="categories-2" class="widget widget_categories">
                            <h5 class="widgettitle">Arşiv</h5>
                            <ul>
                                {%for year in years %}
                                <li class="cat-item cat-item-3"><a
                                        href="{%url 'yaratici:posts_byyear' year=year%}">{{year}}</a>
                                </li>
                                {%endfor%}
                            </ul>

                        </div>
                        <div id="categories-2" class="widget widget_categories">
                            <h5 class="widgettitle">Kategoriler</h5>
                            <ul>
                                {%for category in categories %}
                                <li class="cat-item cat-item-3"><a
                                        href="{%url 'yaratici:posts_bytag' slug=category.slug %}">{{category}}</a>
                                </li>
                                {%endfor%}
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {%endblock%}

mysite/templates/yaratici/show-question.html
{% extends './base.html'%}
{% load static %}

{% block title %} {% endblock  %}
{% block meta %} {% endblock  %}

{% block css %}
<style>
    ul {
        list-style-type: none;

    }

    li {
        padding-left: 10px;
        padding-top: 3px;
    }

    .card-title {
        font-size: 2rem;
        line-height: 1.2;

    }

    #question {
        border-radius: 50px;
        border: 20px solid transparent;
        border-color: #F3A5A5;
        padding: 15px;

    }

    .related-question-post {
        display: flex;
        flex-direction: column;
        align-items: left;
        margin-top: 20px;
        font-size: medium;

    }

    .related-question-post-container {
        margin-top: 20px;
    }
    .card-title{
        padding-left: 35px;
    }

    body{
        text-align: left;
    }
</style>
{% endblock css %}


{%block content%}
<div id="page" class="site">
    <div class="header-wrapper">
        <div class='header  color-overlay  custom-mobile-image'
            style='background-image:url("https://yaraticicocugum.com/anasayfa/wp-content/themes/highlight/assets/images/hero-inner.jpg"); background-color:#6a73da'
            data-parallax-depth='20'>
            <div class="background-overlay"></div>
            <div class="inner-header-description gridContainer">
                <div class="row header-description-row">
                    <div class="col-xs col-xs-12">
                        <h1 class="hero-title align-center">
                            Haftanın Sorusu </h1>
                            <div id="newquestion"></div>
                    </div>
                </div>
            </div>
            <script>
                if (window.mesmerizeSetHeaderTopSpacing) {
                    window.mesmerizeSetHeaderTopSpacing();
                }
            </script>
        </div>
    </div>
    

    {% if messages %}
    {% for message in messages %}
    <div id="message"style="background-color:#F8D7DA; font-size:20px; color:#82333A; padding:20px"class="alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
        <i class="fas fa-exclamation-triangle"></i>
        {{ message }}
        
      
    </div>
    {% endfor %}
    {% endif %}

    
    <br>
    <br>

    <div id='page-content' class="content blog-page">
        <div class="gridContainer gridContainer content">
            <div class="row">

                <!-- Main Area -->
                <div class="col-xs-12 col-sm-8 col-md-8">
                    <div class="post-list row" data-no-masonry='1'>
                        <!-- START OF BLOG POST -->
                        <div class="container">
                            <div class="row">
                                <!-- start of question -->
                                <div class="col-sm-12 col-lg-8 ">
                                    <div id=question class="card">
                                        <div class="card-header text-center">
                                            Haftanın Sorusu
                                        </div>
                                        <br>
                                        <div class="card-body">
                                            <h5 class="card-title">{{question}}</h5>
                                            <ul class="list-group text-left ">
                                                <form method="POST" action="{% url 'yaratici:get_question' %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" value="{{question.id}}" name="question_id">
                                                    {% for choice in question.choices_set.all %}
                                                    <li class="list-group-item">
                                                        <input class="col-1" type="radio" value="{{choice.choice}}"
                                                            id="{{choice.id}}" name="response">
                                                        <span class='col-11'>{{choice.choice|safe}}</span>
                                                    </li>
                                                    {%endfor%}
                                                    <br>
                                                    <button style="background-color: #6977DF; border:0px" type="submit"
                                                        class="button">Sonuçları Göster</button>
                                                </form>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <!-- end of question -->
                            </div>
                        </div>
                        <!-- END OF BLOG POST -->
                    </div>
                </div>

                <!-- SİDEBAR -->
                <!-- SİDEBAR -->
                <div class="sidebar col-sm-4 col-md-3">
                    <div class="panel bg-color-white">
                        
                        <div id="recent-posts-2" class="widget widget_recent_entries">
                            <h5 class="widgettitle">Son Yazılar</h5>
                            <ul>
                                {%for post in sidebarposts %}
                                <li>
                                    <a href="{%url 'yaratici:show_post' slug=post.slug%}"
                                        aria-current="page">{{post.title}}</a>
                                </li>
                                
                                {%endfor%}
                                <li>
                                    <a href="{%url 'yaratici:posts'%}"
                                        aria-current="page"><small> Tüm yazılar</small></a>
                                </li>
                            </ul>

                        </div>
                       
                        <div id="categories-2" class="widget widget_categories">
                            <h5 class="widgettitle">Arşiv</h5>
                            <ul>
                                {%for year in years %}
                                <li class="cat-item cat-item-3"><a
                                        href="{%url 'yaratici:posts_byyear' year=year%}">{{year}}</a>
                                </li>
                                {%endfor%}
                            </ul>

                        </div>
                        <div id="categories-2" class="widget widget_categories">
                            <h5 class="widgettitle">Kategoriler</h5>
                            <ul>
                                {%for category in categories %}
                                <li class="cat-item cat-item-3"><a
                                        href="{%url 'yaratici:posts_bytag' slug=category.slug %}">{{category}}</a>
                                </li>
                                {%endfor%}
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>





{%endblock%}